keys:
  - &diogo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4wh28BWFp9Jql1BEzEO5RjtlmzBqRSXjGo03a8qXdd

  - &lumi age1wkmkx4ru8lcgzrkjxyc7u77s9vdrneengltz6wjsy600lh2n8smqut342x

creation_rules:
  - path_regex: ^secrets/diogo\.yaml$
    key_groups:
      - age:
          - *diogo

  - path_regex: ^secrets/services/[^/]+\.yaml$
    key_groups:
      - age:
          - *diogo
          - *lumi
